# Generated by Django 4.0.2 on 2022-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('qurams', models.TextField(verbose_name='Анонс')),
            ],
            options={
                'verbose_name': 'Құрамы',
                'verbose_name_plural': 'Құрамдар',
            },
        ),
    ]
