# Generated by Django 4.0.2 on 2022-03-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_quram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qundylyq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=50, verbose_name='Тағам')),
                ('aquz', models.CharField(max_length=50, verbose_name='Ақуыз')),
                ('mai', models.CharField(max_length=50, verbose_name='Май')),
                ('ksutek', models.CharField(max_length=50, verbose_name='Көмірсутек')),
            ],
            options={
                'verbose_name': 'Құндылық',
                'verbose_name_plural': 'Құндылықтары',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
