# Generated by Django 4.0.2 on 2022-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_qundylyq_alter_articles_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырып')),
                ('is_published', models.BooleanField(default='True', verbose_name='Шығармашылық')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Сипаттамасы'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Жариялаған күні'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(verbose_name='Толық сипаттама'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/', verbose_name='Еңгізетін суреті'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тағам аты'),
        ),
        migrations.AlterField(
            model_name='quram',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='quram',
            name='qurams',
            field=models.TextField(verbose_name='Құрам'),
        ),
    ]
