# Generated by Django 4.0.2 on 2022-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_logs_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='imgs',
            field=models.FileField(blank=True, null=True, upload_to='main/img/', verbose_name='Upload media'),
        ),
    ]
