# Generated by Django 4.0.2 on 2022-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_articles_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='main/img/', verbose_name='Upload Video'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/', verbose_name='Upload image'),
        ),
    ]
